# Generated by Django 6.0.6 on 2026-07-03 20:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0003_proyecto_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, max_length=11, verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='GuiaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, verbose_name='N° Guía')),
                ('fecha_emision', models.DateField(verbose_name='Fecha emisión')),
                ('fecha_traslado', models.DateField(verbose_name='Fecha traslado')),
                ('motivo', models.CharField(choices=[('TRASLADO_OBRA', 'Traslado a obra'), ('TRASLADO_ALMACEN', 'Traslado a almacén'), ('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('DEVOLUCION', 'Devolución'), ('OTRO', 'Otro')], default='TRASLADO_OBRA', max_length=20, verbose_name='Motivo')),
                ('origen', models.CharField(max_length=300, verbose_name='Punto de partida')),
                ('destino', models.CharField(max_length=300, verbose_name='Punto de llegada')),
                ('placa', models.CharField(blank=True, max_length=15, verbose_name='Placa vehículo')),
                ('conductor', models.CharField(blank=True, max_length=100, verbose_name='Conductor')),
                ('licencia', models.CharField(blank=True, max_length=20, verbose_name='N° Licencia')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso bruto (kg)')),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='proyectos.proyecto')),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias', to='logistica.transportista')),
            ],
            options={
                'verbose_name': 'Guía de Remisión',
                'verbose_name_plural': 'Guías de Remisión',
                'ordering': ['-fecha_emision', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='DetalleGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=400, verbose_name='Descripción')),
                ('unidad', models.CharField(blank=True, max_length=20, verbose_name='Unidad')),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Cantidad')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='logistica.guiaremision')),
            ],
            options={
                'verbose_name': 'Detalle de Guía',
            },
        ),
    ]
