# Generated by Django 6.0.6 on 2026-07-13 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
        ('requerimientos', '0008_requerimiento_aprobacion_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaremision',
            name='requerimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_remision', to='requerimientos.requerimiento'),
        ),
    ]
