# Generated by Django 6.0.6 on 2026-08-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_guiaremision_requerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaremision',
            name='vista_por_almacen',
            field=models.BooleanField(default=False),
        ),
    ]
