# Generated by Django 6.0.6 on 2026-10-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0014_cotizacion_datos_proveedor'),
        ('logistica', '0003_guiaremision_vista_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaremision',
            name='cotizaciones',
            field=models.ManyToManyField(blank=True, related_name='guias_remision', to='almacen.cotizacion'),
        ),
    ]
