# Generated by Django 6.0.6 on 2026-10-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_guiaremision_cotizaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaremision',
            name='motivo_otro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Otro motivo'),
        ),
    ]
