# Generated by Django 6.0.6 on 2026-06-23 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('proveedor', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unidad', models.CharField(choices=[('BLS', 'Bolsa (BLS)'), ('CAJ', 'Caja (CAJ)'), ('GAL', 'Galón (GAL)'), ('GL', 'Global (GL)'), ('JGO', 'Juego'), ('KG', 'Kilogramo (KG)'), ('L', 'Litro (L)'), ('M2', 'M2'), ('M3', 'M3'), ('ML', 'Metro Lineal (ML)'), ('UND', 'Unidad (UND)'), ('PLG', 'Pulgada (PLG)'), ('MT', 'Metro (MT)'), ('TN', 'Tonelada (TN)'), ('RLL', 'Rollo (RLL)'), ('PAR', 'Par'), ('PZA', 'Pieza (PZA)'), ('GR', 'Gramo (GR)'), ('SET', 'Set')], default='UND', max_length=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almacen.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(default='001', max_length=10)),
                ('numero_guia', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('unidad', models.CharField(choices=[('BLS', 'Bolsa (BLS)'), ('CAJ', 'Caja (CAJ)'), ('GAL', 'Galón (GAL)'), ('GL', 'Global (GL)'), ('JGO', 'Juego'), ('KG', 'Kilogramo (KG)'), ('L', 'Litro (L)'), ('M2', 'M2'), ('M3', 'M3'), ('ML', 'Metro Lineal (ML)'), ('UND', 'Unidad (UND)'), ('PLG', 'Pulgada (PLG)'), ('MT', 'Metro (MT)'), ('TN', 'Tonelada (TN)'), ('RLL', 'Rollo (RLL)'), ('PAR', 'Par'), ('PZA', 'Pieza (PZA)'), ('GR', 'Gramo (GR)'), ('SET', 'Set')], default='UND', max_length=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almacen.entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('MATERIAL', 'Material'), ('EQUIPO', 'Equipo'), ('EPP', 'EPP'), ('UTIL', 'Útil'), ('HERRAMIENTA', 'Herramienta'), ('OTRO', 'Otro')], default='MATERIAL', max_length=20)),
                ('solicitante', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('ATENDIDO', 'Atendido'), ('PARCIAL', 'Atendido Parcial'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'ordering': ['-fecha', '-numero'],
                'unique_together': {('proyecto', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='entrada',
            name='requerimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='almacen.requerimiento'),
        ),
        migrations.CreateModel(
            name='DetalleRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unidad', models.CharField(choices=[('BLS', 'Bolsa (BLS)'), ('CAJ', 'Caja (CAJ)'), ('GAL', 'Galón (GAL)'), ('GL', 'Global (GL)'), ('JGO', 'Juego'), ('KG', 'Kilogramo (KG)'), ('L', 'Litro (L)'), ('M2', 'M2'), ('M3', 'M3'), ('ML', 'Metro Lineal (ML)'), ('UND', 'Unidad (UND)'), ('PLG', 'Pulgada (PLG)'), ('MT', 'Metro (MT)'), ('TN', 'Tonelada (TN)'), ('RLL', 'Rollo (RLL)'), ('PAR', 'Par'), ('PZA', 'Pieza (PZA)'), ('GR', 'Gramo (GR)'), ('SET', 'Set')], default='UND', max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=300)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almacen.requerimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('destino', models.CharField(blank=True, max_length=200)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('unidad', models.CharField(choices=[('BLS', 'Bolsa (BLS)'), ('CAJ', 'Caja (CAJ)'), ('GAL', 'Galón (GAL)'), ('GL', 'Global (GL)'), ('JGO', 'Juego'), ('KG', 'Kilogramo (KG)'), ('L', 'Litro (L)'), ('M2', 'M2'), ('M3', 'M3'), ('ML', 'Metro Lineal (ML)'), ('UND', 'Unidad (UND)'), ('PLG', 'Pulgada (PLG)'), ('MT', 'Metro (MT)'), ('TN', 'Tonelada (TN)'), ('RLL', 'Rollo (RLL)'), ('PAR', 'Par'), ('PZA', 'Pieza (PZA)'), ('GR', 'Gramo (GR)'), ('SET', 'Set')], default='UND', max_length=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almacen.salida')),
            ],
        ),
    ]
