# Generated by Django 6.0.6 on 2026-06-25 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        ('catalogo', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('proveedor', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('PARCIAL', 'Recibida Parcial'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('plazo_entrega', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='almacen.cotizacion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='proyectos.proyecto')),
                ('requerimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='almacen.requerimiento')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha', '-numero'],
                'unique_together': {('proyecto', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('unidad', models.CharField(choices=[('BLS', 'Bolsa (BLS)'), ('CAJ', 'Caja (CAJ)'), ('GAL', 'Galón (GAL)'), ('GL', 'Global (GL)'), ('JGO', 'Juego'), ('KG', 'Kilogramo (KG)'), ('L', 'Litro (L)'), ('M2', 'M2'), ('M3', 'M3'), ('ML', 'Metro Lineal (ML)'), ('UND', 'Unidad (UND)'), ('PLG', 'Pulgada (PLG)'), ('MT', 'Metro (MT)'), ('TN', 'Tonelada (TN)'), ('RLL', 'Rollo (RLL)'), ('PAR', 'Par'), ('PZA', 'Pieza (PZA)'), ('GR', 'Gramo (GR)'), ('SET', 'Set')], default='UND', max_length=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almacen.ordencompra')),
            ],
        ),
    ]
