# Generated by Django 6.0.6 on 2026-07-03 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_add_orden_compra'),
        ('presupuesto', '0008_parcial_partida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleentrada',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleordencompra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detallerequerimiento',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detallesalida',
            name='producto',
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presupuesto.insumopresupuesto'),
        ),
        migrations.AddField(
            model_name='detalleentrada',
            name='descripcion',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='detalleentrada',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presupuesto.insumopresupuesto'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='descripcion',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presupuesto.insumopresupuesto'),
        ),
        migrations.AddField(
            model_name='detallerequerimiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='detallerequerimiento',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presupuesto.insumopresupuesto'),
        ),
        migrations.AddField(
            model_name='detallesalida',
            name='descripcion',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='detallesalida',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presupuesto.insumopresupuesto'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='unidad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='detalleentrada',
            name='unidad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='unidad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='detallerequerimiento',
            name='unidad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='detallesalida',
            name='unidad',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
