# Generated by Django 6.0.6 on 2026-07-05 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_remove_detallecotizacion_producto_and_more'),
        ('requerimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requerimiento',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='requerimiento',
            name='proyecto',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='requerimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='requerimientos.requerimiento'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='requerimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='requerimientos.requerimiento'),
        ),
        migrations.DeleteModel(
            name='DetalleRequerimiento',
        ),
        migrations.DeleteModel(
            name='Requerimiento',
        ),
    ]
