# Generated by Django 6.0.6 on 2026-07-05 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_alter_requerimiento_unique_together_and_more'),
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='guia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada', to='logistica.guiaremision'),
        ),
    ]
