# Generated by Django 6.0.6 on 2026-07-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_entrada_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='entrada',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
