# Generated by Django 6.0.6 on 2026-07-05 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_entrada_estado_entrada_motivo_rechazo'),
        ('requerimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='requerimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='requerimientos.requerimiento'),
        ),
    ]
