# Generated by Django 6.0.6 on 2026-07-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_salida_requerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones/pdfs/'),
        ),
    ]
