# Generated by Django 6.0.6 on 2026-08-04 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_cotizacion_archivo_pdf'),
        ('requerimientos', '0012_historialrevision_anular_recuperar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='requerimiento_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_origen', to='requerimientos.requerimiento'),
        ),
    ]
