# Generated by Django 6.0.6 on 2026-08-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0009_cot_requerimiento_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentrada',
            name='observaciones',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
