# Generated by Django 6.0.6 on 2026-08-11 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0010_detalleentrada_observaciones'),
        ('logistica', '0003_guiaremision_vista_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesalida',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='logistica.guiaremision'),
        ),
        migrations.AddField(
            model_name='detallesalida',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salida',
            name='factura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salida',
            name='proveedor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
