# Generated by Django 6.0.6 on 2026-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0013_backfill_stock_sin_filtro_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='proveedor',
            field=models.CharField(max_length=200, verbose_name='Razón social'),
        ),
    ]
