# Generated by Django 6.0.6 on 2026-10-03 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0014_cotizacion_datos_proveedor'),
        ('logistica', '0005_guiaremision_motivo_otro'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentrada',
            name='detalle_guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='logistica.detalleguia'),
        ),
    ]
