# Generated by Django 6.0.6 on 2026-06-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=300)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('FORMULACION', 'En Formulación'), ('EJECUCION', 'En Ejecución'), ('PAUSADO', 'Pausado'), ('TERMINADO', 'Terminado'), ('LIQUIDADO', 'Liquidado')], default='FORMULACION', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
    ]
