# Generated by Django 6.0.6 on 2026-06-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyectomiembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
