# Generated by Django 6.0.6 on 2026-07-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='plazo_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
