# Generated by Django 6.0.6 on 2026-07-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_proyecto_plazo_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='activo',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='empresa_ejecutora',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
