# Generated by Django 6.0.6 on 2026-08-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_remove_proyecto_activo_proyecto_empresa_ejecutora'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cargo_responsable',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='sector',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
