# Generated by Django 6.0.6 on 2026-07-05 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuesto', '0009_add_insumo_total'),
        ('proyectos', '0003_proyecto_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('MATERIAL', 'Material'), ('EQUIPO', 'Equipo'), ('EPP', 'EPP'), ('UTIL', 'Útil'), ('HERRAMIENTA', 'Herramienta'), ('OTRO', 'Otro')], default='MATERIAL', max_length=20)),
                ('solicitante', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado a Logística'), ('APROBADO', 'Aprobado'), ('ATENDIDO', 'Atendido'), ('PARCIAL', 'Atendido Parcial'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'ordering': ['-fecha', '-numero'],
                'unique_together': {('proyecto', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='DetalleRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=400)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=300)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presupuesto.insumopresupuesto')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='requerimientos.requerimiento')),
            ],
        ),
    ]
