# Generated by Django 6.0.6 on 2026-07-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='cargo_solicitante',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='obra',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='sector_obra',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
