# Generated by Django 6.0.6 on 2026-07-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0002_requerimiento_cargo_solicitante_requerimiento_obra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='numero_global',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
