# Generated by Django 6.0.6 on 2026-07-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0003_requerimiento_numero_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimiento',
            name='cantidad_requerida',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='detallerequerimiento',
            name='justificacion',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
