# Generated by Django 6.0.6 on 2026-07-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0004_detallerequerimiento_cantidad_requerida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado a Logística'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('ATENDIDO', 'Atendido'), ('PARCIAL', 'Atendido Parcial'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20),
        ),
    ]
