# Generated by Django 6.0.6 on 2026-07-10 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_salida_requerimiento'),
        ('requerimientos', '0005_add_en_revision_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimiento',
            name='cantidad_aprobada',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='cotizacion_pdf',
            field=models.FileField(blank=True, null=True, upload_to='requerimientos/cotizaciones/'),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='cotizacion_sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos', to='almacen.cotizacion'),
        ),
    ]
