# Generated by Django 6.0.6 on 2026-07-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0006_cotizacion_y_cantidad_aprobada'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimiento',
            name='codigo',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
