# Generated by Django 6.0.6 on 2026-07-13 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0011_alter_insumopresupuesto_tipo_and_more'),
        ('requerimientos', '0008_requerimiento_aprobacion_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimiento',
            name='insumo_sustituto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_sustituto', to='presupuesto.insumopresupuesto', verbose_name='Insumo sustituto'),
        ),
    ]
