# Generated by Django 6.0.6 on 2026-07-13 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0011_alter_insumopresupuesto_tipo_and_more'),
        ('requerimientos', '0009_detallerequerimiento_insumo_sustituto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialRevisionReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('ELIMINAR', 'Ítem eliminado'), ('AGREGAR', 'Ítem agregado')], max_length=10)),
                ('descripcion', models.CharField(max_length=400)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15)),
                ('justificacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presupuesto.insumopresupuesto')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_revision', to='requerimientos.requerimiento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de revisión',
                'verbose_name_plural': 'Historial de revisiones',
                'ordering': ['-fecha'],
            },
        ),
    ]
