# Generated by Django 6.0.6 on 2026-08-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0010_historialrevisionreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('SOLICITADO', 'Solicitado por Almacén'), ('ENVIADO', 'Enviado a Logística'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('ATENDIDO', 'Atendido'), ('PARCIAL', 'Atendido Parcial'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20),
        ),
    ]
