# Generated by Django 6.0.6 on 2026-08-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0011_alter_requerimiento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialrevisionreq',
            name='accion',
            field=models.CharField(choices=[('ELIMINAR', 'Ítem eliminado'), ('AGREGAR', 'Ítem agregado'), ('ANULAR', 'Requerimiento anulado'), ('RECUPERAR', 'Requerimiento recuperado')], max_length=10),
        ),
    ]
