# Generated by Django 6.0.6 on 2026-08-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0012_historialrevision_anular_recuperar'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='es_ajuste',
            field=models.BooleanField(default=False),
        ),
    ]
