# Generated by Django 6.0.6 on 2026-10-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0014_requerimiento_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('SOLICITADO', 'Solicitado por Almacén'), ('ENVIADO', 'Enviado a Logística'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('COTIZADO', 'Cotizado'), ('ATENDIDO', 'Atendido'), ('PARCIAL', 'Atendido Parcial'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20),
        ),
    ]
