# Generated by Django 6.0.6 on 2026-06-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('ruc', models.CharField(blank=True, max_length=11, verbose_name='RUC')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('moneda', models.CharField(default='S/.', max_length=10, verbose_name='Moneda')),
                ('igv', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='IGV (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
            },
        ),
    ]
