# Generated by Django 6.0.6 on 2026-06-27 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('puede_crear_proyectos', models.BooleanField(default=False)),
                ('puede_eliminar_proyectos', models.BooleanField(default=False)),
                ('puede_ver_presupuesto', models.BooleanField(default=False)),
                ('puede_editar_presupuesto', models.BooleanField(default=False)),
                ('puede_ver_almacen', models.BooleanField(default=False)),
                ('puede_crear_requerimientos', models.BooleanField(default=False)),
                ('puede_aprobar_requerimientos', models.BooleanField(default=False)),
                ('puede_gestionar_entradas', models.BooleanField(default=False)),
                ('puede_gestionar_salidas', models.BooleanField(default=False)),
                ('puede_gestionar_cotizaciones', models.BooleanField(default=False)),
                ('puede_gestionar_oc', models.BooleanField(default=False)),
                ('puede_editar_catalogo', models.BooleanField(default=False)),
                ('puede_administrar_usuarios', models.BooleanField(default=False)),
                ('puede_administrar_roles', models.BooleanField(default=False)),
                ('puede_configurar_empresa', models.BooleanField(default=False)),
                ('acceso_todos_proyectos', models.BooleanField(default=False)),
                ('es_superadmin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='configuracion.rol')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
            },
        ),
    ]
