# Generated by Django 6.0.6 on 2026-06-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_rol_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='puede_gestionar_maquinaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_ver_maquinaria',
            field=models.BooleanField(default=False),
        ),
    ]
