# Generated by Django 6.0.6 on 2026-07-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_rol_puede_gestionar_maquinaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='puede_gestionar_logistica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_ver_logistica',
            field=models.BooleanField(default=True),
        ),
    ]
