# Generated by Django 6.0.6 on 2026-07-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_configempresa_logo_parametrosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSunat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regimen_tributario', models.CharField(blank=True, choices=[('RG', 'Régimen General'), ('RER', 'Régimen Especial de Renta'), ('RUS', 'Nuevo RUS'), ('MYPE', 'Régimen MYPE Tributario')], max_length=10, verbose_name='Régimen Tributario')),
                ('usuario_sol', models.CharField(blank=True, max_length=100, verbose_name='Usuario SOL')),
                ('clave_sol', models.CharField(blank=True, max_length=100, verbose_name='Clave SOL')),
                ('tipo_comprobante', models.CharField(blank=True, max_length=20, verbose_name='Tipo de Comprobante por defecto')),
                ('serie_factura', models.CharField(blank=True, max_length=10, verbose_name='Serie Factura')),
                ('serie_boleta', models.CharField(blank=True, max_length=10, verbose_name='Serie Boleta')),
                ('numero_correlativo', models.CharField(blank=True, max_length=20, verbose_name='N° Correlativo')),
                ('ose', models.CharField(blank=True, max_length=100, verbose_name='OSE / PSE')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración SUNAT',
            },
        ),
    ]
