# Generated by Django 6.0.6 on 2026-07-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_configsunat'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
