# Generated by Django 6.0.6 on 2026-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_unidadmedida'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='aliases',
            field=models.TextField(blank=True, help_text='Variantes separadas por coma que se normalizan a este código al importar. Ej: hh, hora hombre, horas hombre', verbose_name='Aliases'),
        ),
    ]
