# Generated by Django 6.0.6 on 2026-07-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_unidadmedida_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre oficial')),
                ('variantes', models.TextField(blank=True, help_text='Palabras clave separadas por coma que identifican este cargo en archivos importados.', verbose_name='Variantes')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cargo de Mano de Obra',
                'verbose_name_plural': 'Cargos de Mano de Obra',
                'ordering': ['orden', 'codigo'],
            },
        ),
    ]
