# Generated by Django 6.0.6 on 2026-07-10 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0010_cargomanoobra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParametroSistema',
        ),
    ]
