# Generated by Django 6.0.6 on 2026-07-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0011_remove_parametrosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='puede_gestionar_abastecimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_gestionar_almacen_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_gestionar_cotizaciones_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_gestionar_ctrl_maq_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_gestionar_inventarios_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_revisar_reqs_log',
            field=models.BooleanField(default=False),
        ),
    ]
