# Generated by Django 6.0.6 on 2026-07-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0012_rol_permisos_logistica_submodulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='puede_ver_dashboard',
            field=models.BooleanField(default=True),
        ),
    ]
