# Generated by Django 6.0.6 on 2026-07-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0015_configdecimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaDeteccionInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EQUIPO', 'Equipo / Maquinaria'), ('SUBCONTRATO', 'Subcontrato'), ('MATERIAL', 'Material'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de insumo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la regla')),
                ('palabras', models.TextField(blank=True, help_text='Palabras clave separadas por coma. Si alguna aparece en la descripción del insumo, se asigna este tipo.', verbose_name='Palabras clave')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Regla de Detección de Insumo',
                'verbose_name_plural': 'Reglas de Detección de Insumos',
                'ordering': ['tipo', 'orden', 'nombre'],
            },
        ),
    ]
