# Generated by Django 6.0.6 on 2026-07-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0016_regla_deteccion_insumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('REQUERIMIENTOS', 'Requerimientos'), ('LOGISTICA', 'Logística'), ('PRESUPUESTO', 'Presupuesto'), ('ALMACEN', 'Almacén'), ('MAQUINARIA', 'Maquinaria'), ('CONFIGURACION', 'Configuración'), ('PROYECTOS', 'Proyectos'), ('OTRO', 'Otro')], default='OTRO', max_length=30, verbose_name='Módulo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reporte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='regladeteccioninsumo',
            name='tipo',
            field=models.CharField(choices=[('EQUIPO', 'Equipo'), ('MAQUINARIA', 'Maquinaria'), ('SUBCONTRATO', 'Subcontrato'), ('MATERIAL', 'Material'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de insumo'),
        ),
        migrations.CreateModel(
            name='ImagenReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='reportes/', verbose_name='Imagen')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='configuracion.reporte')),
            ],
        ),
    ]
