# Generated by Django 6.0.6 on 2026-08-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0017_reporte_imagen_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='puede_configurar_proyecto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_gestionar_personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_ver_actividad',
            field=models.BooleanField(default=False),
        ),
    ]
