# Generated by Django 6.0.6 on 2026-08-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0019_seed_roles_operativos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configempresa',
            name='color_primario',
            field=models.CharField(blank=True, default='#2563eb', max_length=7, verbose_name='Color Primario'),
        ),
    ]
