# Generated by Django 6.0.6 on 2026-08-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0020_configempresa_color_primario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configempresa',
            name='imagen_marca',
            field=models.ImageField(blank=True, null=True, upload_to='empresa/marca/', verbose_name='Imagen de Marca (sidebar)'),
        ),
    ]
