# Generated by Django 6.0.6 on 2026-06-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('categoria', models.CharField(choices=[('MATERIAL', 'Material'), ('EQUIPO', 'Equipo'), ('EPP', 'EPP'), ('UTIL', 'Útil'), ('HERRAMIENTA', 'Herramienta'), ('OTRO', 'Otro')], default='MATERIAL', max_length=20)),
                ('unidad', models.CharField(choices=[('BLS', 'Bolsa (BLS)'), ('CAJ', 'Caja (CAJ)'), ('GAL', 'Galón (GAL)'), ('GL', 'Global (GL)'), ('JGO', 'Juego'), ('KG', 'Kilogramo (KG)'), ('L', 'Litro (L)'), ('M2', 'M2'), ('M3', 'M3'), ('ML', 'Metro Lineal (ML)'), ('UND', 'Unidad (UND)'), ('PLG', 'Pulgada (PLG)'), ('MT', 'Metro (MT)'), ('TN', 'Tonelada (TN)'), ('RLL', 'Rollo (RLL)'), ('PAR', 'Par'), ('PZA', 'Pieza (PZA)'), ('GR', 'Gramo (GR)'), ('SET', 'Set')], default='UND', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria', 'codigo'],
            },
        ),
    ]
