# Generated by Django 6.0.6 on 2026-06-23 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Presupuesto Principal', max_length=200)),
                ('archivo_origen', models.CharField(blank=True, max_length=300)),
                ('fecha_importacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=500)),
                ('nivel', models.PositiveSmallIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='presupuesto.partida')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='presupuesto.presupuesto')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RecursoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MATERIAL', 'Material'), ('MANO_OBRA', 'Mano de Obra'), ('EQUIPO', 'Equipo/Maquinaria'), ('SUBCONTRATO', 'Subcontrato'), ('OTRO', 'Otro')], default='MATERIAL', max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(max_length=400)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='presupuesto.partida')),
            ],
            options={
                'verbose_name': 'Recurso de Partida',
                'verbose_name_plural': 'Recursos de Partida',
            },
        ),
    ]
