# Generated by Django 6.0.6 on 2026-06-25 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MATERIAL', 'Material'), ('MANO_OBRA', 'Mano de Obra'), ('EQUIPO', 'Equipo/Maquinaria'), ('SUBCONTRATO', 'Subcontrato'), ('OTRO', 'Otro')], default='MATERIAL', max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=60)),
                ('descripcion', models.CharField(max_length=400)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='presupuesto.presupuesto')),
            ],
            options={
                'verbose_name': 'Insumo del Presupuesto',
                'verbose_name_plural': 'Insumos del Presupuesto',
                'ordering': ['tipo', 'descripcion'],
            },
        ),
    ]
