# Generated by Django 6.0.6 on 2026-06-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_add_insumo_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='partida_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variaciones', to='presupuesto.partida'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='presupuesto_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones', to='presupuesto.presupuesto'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='tipo',
            field=models.CharField(choices=[('CONTRACTUAL', 'Contractual'), ('ADICIONAL', 'Adicional'), ('DEDUCTIVO', 'Deductivo')], default='CONTRACTUAL', max_length=20),
        ),
    ]
