# Generated by Django 6.0.6 on 2026-06-28 17:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0005_presupuesto_refactor'),
        ('proyectos', '0003_proyecto_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'verbose_name': 'Presupuesto', 'verbose_name_plural': 'Presupuestos'},
        ),
        migrations.RemoveConstraint(
            model_name='modificacion',
            name='unique_modificacion_numero',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='gastos_generales_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Gastos Generales (%)'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='igv_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('18'), max_digits=6, verbose_name='IGV (%)'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='utilidad_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Utilidad (%)'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='nombre',
            field=models.CharField(default='Presupuesto Contractual', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='modificacion',
            unique_together={('proyecto', 'tipo', 'numero')},
        ),
    ]
