# Generated by Django 6.0.6 on 2026-06-29 18:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0006_alter_presupuesto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='supervision_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Supervisión (% sobre Costo Total de Obra)'),
        ),
    ]
