# Generated by Django 6.0.6 on 2026-06-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0007_supervision_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='parcial',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True, verbose_name='Total calculado'),
        ),
    ]
