# Generated by Django 6.0.6 on 2026-07-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0008_parcial_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumopresupuesto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
