# Generated by Django 6.0.6 on 2026-07-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0010_insumo_cantidad_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumopresupuesto',
            name='tipo',
            field=models.CharField(choices=[('MATERIAL', 'Material'), ('MANO_OBRA', 'Mano de Obra'), ('EQUIPO', 'Equipo'), ('MAQUINARIA', 'Maquinaria'), ('SUBCONTRATO', 'Subcontrato'), ('OTRO', 'Otro')], default='MATERIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='recursopartida',
            name='tipo',
            field=models.CharField(choices=[('MATERIAL', 'Material'), ('MANO_OBRA', 'Mano de Obra'), ('EQUIPO', 'Equipo'), ('MAQUINARIA', 'Maquinaria'), ('SUBCONTRATO', 'Subcontrato'), ('OTRO', 'Otro')], default='MATERIAL', max_length=20),
        ),
    ]
