# Generated by Django 6.0.6 on 2026-08-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0011_alter_insumopresupuesto_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumopresupuesto',
            name='stock_almacen',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
