# Generated by Django 6.0.6 on 2026-07-03 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('IMPORTAR', 'Importar'), ('APROBAR', 'Aprobar'), ('ANULAR', 'Anular'), ('LOGIN', 'Iniciar sesión'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('modulo', models.CharField(choices=[('Proyectos', 'Proyectos'), ('Presupuesto', 'Presupuesto'), ('Almacén', 'Almacén'), ('Maquinaria', 'Maquinaria'), ('Catálogo', 'Catálogo'), ('Configuración', 'Configuración'), ('Sesión', 'Sesión')], default='Otro', max_length=50)),
                ('descripcion', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Acción',
                'verbose_name_plural': 'Registro de Actividad',
                'ordering': ['-fecha'],
            },
        ),
    ]
