# Generated by Django 6.0.6 on 2026-07-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroaccion',
            name='modulo',
            field=models.CharField(choices=[('Proyectos', 'Proyectos'), ('Presupuesto', 'Presupuesto'), ('Almacén', 'Almacén'), ('Maquinaria', 'Maquinaria'), ('Logística', 'Logística'), ('Catálogo', 'Catálogo'), ('Configuración', 'Configuración'), ('Sesión', 'Sesión')], default='Otro', max_length=50),
        ),
    ]
