# Generated by Django 6.0.6 on 2026-06-29 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuesto', '0006_alter_presupuesto_options_and_more'),
        ('proyectos', '0003_proyecto_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuadrilla',
                'verbose_name_plural': 'Cuadrillas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('EQUIPO', 'Equipo'), ('VEHICULO', 'Vehículo'), ('HERRAMIENTA', 'Herramienta'), ('OTRO', 'Otro')], default='EQUIPO', max_length=20)),
                ('costo_hora', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('placa', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinaria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('costo_hora', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Personal',
                'verbose_name_plural': 'Tipos de Personal',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, default=8, max_digits=6)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinaria.cuadrilla')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_cuadrilla', to='presupuesto.partida')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_cuadrilla', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Registro Diario de Cuadrilla',
                'verbose_name_plural': 'Registros Diarios de Cuadrilla',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, default=8, max_digits=6)),
                ('operador', models.CharField(blank=True, max_length=200)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinaria.maquinaria')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_maquinaria', to='presupuesto.partida')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_maquinaria', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Registro de Maquinaria',
                'verbose_name_plural': 'Registros de Maquinaria',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegranteCuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='maquinaria.cuadrilla')),
                ('tipo_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinaria.tipopersonal')),
            ],
            options={
                'verbose_name': 'Integrante de Cuadrilla',
                'verbose_name_plural': 'Integrantes de Cuadrilla',
                'unique_together': {('cuadrilla', 'tipo_personal')},
            },
        ),
    ]
