# Generated by Django 6.0.6 on 2026-07-05 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromaquinaria',
            name='codigo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='registromaquinaria',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='registromaquinaria',
            name='fecha_llegada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromaquinaria',
            name='fecha_reinicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromaquinaria',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromaquinaria',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registromaquinaria',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('MENSUAL', 'Mensual'), ('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('SECA', 'Maquinaria Seca')], max_length=15),
        ),
        migrations.AddField(
            model_name='registromaquinaria',
            name='modalidad_costo',
            field=models.CharField(blank=True, choices=[('MENSUAL', 'Mensual'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal')], max_length=15),
        ),
        migrations.AddField(
            model_name='registromaquinaria',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registromaquinaria',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registromaquinaria',
            name='placa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='registromaquinaria',
            name='propietario',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registromaquinaria',
            name='tipo_equipo',
            field=models.CharField(blank=True, choices=[('CAMIONETA', 'Camioneta'), ('TRACTOR', 'Tractor'), ('RETROEXCAVADORA', 'Retroexcavadora'), ('EXCAVADORA', 'Excavadora'), ('CARGADOR', 'Cargador Frontal'), ('VOLQUETE', 'Volquete'), ('GRUA', 'Grúa'), ('COMPACTADORA', 'Compactadora'), ('MOTONIVELADORA', 'Motoniveladora'), ('BUS', 'Bus / Minibús'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registromaquinaria',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registromaquinaria',
            name='maquinaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maquinaria.maquinaria'),
        ),
    ]
