# Generated by Django 6.0.6 on 2026-07-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0006_liquidacion_y_campos_parte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='costo_hora',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Costo por hora'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='modalidad_costo',
            field=models.CharField(blank=True, choices=[('MENSUAL', 'Mensual (tarifa fija)'), ('SECA', 'Maquinaria Seca (por hora)'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal')], max_length=15, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='placa',
            field=models.CharField(blank=True, max_length=20, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='tipo_equipo',
            field=models.CharField(blank=True, choices=[('CAMIONETA', 'Camioneta'), ('TRACTOR', 'Tractor'), ('RETROEXCAVADORA', 'Retroexcavadora'), ('EXCAVADORA', 'Excavadora'), ('CARGADOR', 'Cargador Frontal'), ('VOLQUETE', 'Volquete'), ('COMPRESORA', 'Compresora'), ('RODILLO', 'Rodillo'), ('ROCK_DRILL', 'Rock Drill'), ('GRUA', 'Grúa'), ('COMPACTADORA', 'Compactadora'), ('MOTONIVELADORA', 'Motoniveladora'), ('BUS', 'Bus / Minibús'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de equipo'),
        ),
        migrations.AlterField(
            model_name='registromaquinaria',
            name='modalidad_costo',
            field=models.CharField(blank=True, choices=[('MENSUAL', 'Mensual (tarifa fija)'), ('SECA', 'Maquinaria Seca (por hora)'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal')], max_length=15),
        ),
        migrations.AlterField(
            model_name='registromaquinaria',
            name='tipo_equipo',
            field=models.CharField(blank=True, choices=[('CAMIONETA', 'Camioneta'), ('TRACTOR', 'Tractor'), ('RETROEXCAVADORA', 'Retroexcavadora'), ('EXCAVADORA', 'Excavadora'), ('CARGADOR', 'Cargador Frontal'), ('VOLQUETE', 'Volquete'), ('COMPRESORA', 'Compresora'), ('RODILLO', 'Rodillo'), ('ROCK_DRILL', 'Rock Drill'), ('GRUA', 'Grúa'), ('COMPACTADORA', 'Compactadora'), ('MOTONIVELADORA', 'Motoniveladora'), ('BUS', 'Bus / Minibús'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
