# Generated by Django 6.0.6 on 2026-08-10 03:13
# Manual: PostgreSQL no puede castear `time` a `numeric` automáticamente.
# Como no hay registros, resolvemos con drop + add.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0007_alter_maquinaria_costo_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(model_name='registromaquinaria', name='hora_entrada'),
        migrations.RemoveField(model_name='registromaquinaria', name='hora_salida'),
        migrations.AddField(
            model_name='registromaquinaria',
            name='hora_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horómetro entrada'),
        ),
        migrations.AddField(
            model_name='registromaquinaria',
            name='hora_salida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horómetro salida'),
        ),
    ]