# Generated by Django 6.0.6 on 2026-08-13 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0009_propietario_datos_estructurados'),
        ('proyectos', '0006_proyecto_cargo_responsable_proyecto_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('dni', models.CharField(blank=True, max_length=15, verbose_name='DNI')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso a obra')),
                ('foto', models.ImageField(blank=True, upload_to='trabajadores/fotos/', verbose_name='Foto')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='proyectos.proyecto')),
                ('tipo_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='maquinaria.tipopersonal', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del documento')),
                ('archivo', models.FileField(upload_to='trabajadores/documentos/', verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='maquinaria.trabajador')),
            ],
            options={
                'verbose_name': 'Documento de Trabajador',
                'verbose_name_plural': 'Documentos de Trabajador',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
